### ISSUE TITLE
Social Page - User not exists

### ISSUE THREAD

**Issue by SarmadAD** [SarmadAD/capstone-project#19]
## Value Preposition

As a User 
i want to be notified 
so that i know that the user not exists. 

## Description
When the user want to add a person to the friend list and the person not exists in the database, the user should be notified about that. 

## Acceptance Criteria
- [ ] open modal after the check if the user exists
- [ ] the modal should inform the user that the friend-user not exists 

## Tasks

(for developers team)

- [ ] create modal
- [ ] create info text and buttons (close and okay for example)
