### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by SarmadAD** [SarmadAD/capstone-project#9]
## Value Preposition
As a user 
I want to navigate between pages 
so that i can access them. 

## Description
<img width="275" alt="Bildschirmfoto 2022-03-24 um 17 29 46" src="https://user-images.githubusercontent.com/52063673/159964594-65ecf82e-00e6-443a-a6a0-f2035e58079c.png">

Scribble / design or text

## Acceptance Criteria
- [x] add nav footer for navigate between the pages
- [x] if a nav item is clicked, the page will switch to the clicked page
- [x] the icon of the clicked page should be highlighted and the others should stay normal

## Tasks

(for developers team)
- [x] add footer
- [x] add logic for color change for the clicked page
- [x] add links to pages
